version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: solhire-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pdtga888
      POSTGRES_DB: solhire
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 